### ISSUE TITLE
Module not found: Can't resolve '@chakra-icons/bootstrap'

### ISSUE THREAD

**Issue by vadhe** [kodingdotninja/chakra-icons#45]
when I'm trying run chore website in local I'm getting this error

![Screenshot from 2022-02-04 20-58-29](https://user-images.githubusercontent.com/36479850/152533212-b4865428-21da-4617-9a82-eb23ad85f681.png)

**Comment by ri7nz** [comment]
I have been update the branch of `chore/website` please update your local branch

**Comment by vadhe** [comment]
my local branch is already up to date

**Comment by ri7nz** [comment]
Could you give me  more information such `node version` and more ? 

Since in the github actions is run well https://github.com/kodingdotninja/chakra-icons/runs/5067860288?check_suite_focus=true

**Comment by vadhe** [comment]
my node version is v14.18.1, anyway I just follow the documentation and then go to the directory website and run yarn dev is correct to run the website in local?

**Comment by ri7nz** [comment]
@vadhe 

Follow this

* clone repository (skip when exist)
* cd the project
* yarn install
* yarn website dev


Just that

**Comment by vadhe** [comment]
when I in-branch main I got this, if I switch in-branch chore/website I'm getting the error before


![Screenshot from 2022-02-05 13-08-29](https://user-images.githubusercontent.com/36479850/152629517-3e14de76-ac14-4a6e-a1ab-9b8cf08bc11f.png)

**Comment by ibrahim4529** [comment]
> when I in-branch main I got this, if I switch in-branch chore/website I'm getting the error before
> 
> ![Screenshot from 2022-02-05 13-08-29](https://user-images.githubusercontent.com/36479850/152629517-3e14de76-ac14-4a6e-a1ab-9b8cf08bc11f.png)

I had same problem but now it has worked.
Here are the steps I did
1. Re-clone this repo
2. checkout to chore/website branch
3. run yarn install
4. run yarn website dev

**Comment by ri7nz** [comment]
@vadhe @ibrahim4529 

The error is expected when you run command `yarn website dev` in the branch `main` (can run correctly when the branch of `chore/website` is merged into `main`). Since, the website is under development phase (chore/website) this error is still happening.


This very basic step to run website development:
* Clone this repository (fork if you want to changes something and PRs later)
* checkout branch `chore/website`
* yarn install 
* yarn clear && yarn install (OPTIONAL: if you already run install in another branch)
* yarn website dev

When the `chore/website` has been updated and you're use `forked`, you can follow this:
* git remote add upstream https://github.com/kodingdotninja/chakra-icons
* git fetch upstream
* git checkout upstream/chore/website
* yarn install
* yarn website dev

Thanks

**Comment by vadhe** [comment]
if this error happens try to yarn build
